// clientes/livros-react/src/LivroDados.js
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import ControleEditora from "./controle/ControleEditora";
import ControleLivro from "./controle/ControleLivros"

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();


function LivroDados(props) {
    let opcoes = controleEditora.getEditoras().map((item) => {
        return(
                <option value={item.codEditora} key={item.codEditora}>{item.nomeEditora}</option>
        )
    })

    const [titulo, setTitulo] = useState(String);
    const [resumo, setResumo] = useState(String);
    const [autores, setAutores] = useState(String);
    const [codEditora, setCodEditora] = useState (Number);

    const navigate = useNavigate();
    
    const tratarCombo= (evento) => {
        setCodEditora(parseInt(evento.target.value))
    }
    const incluir= (evento) =>{
        evento.preventDefault();
        var livro = ({
            codigo : 0,
            codEditora : codEditora,
            titulo : titulo,
            resumo : resumo,
            autores: autores.split('\n')
        })
        setTitulo('');
        setResumo('');
        setAutores('');

        controleLivro.incluir(livro);
        navigate('/lista')

    }

    return (
    <main>
        <form className="form-control" onSubmit={incluir}>
            <h1>Dados do Livro</h1>
            <div className="form-group">
                <label htmlFor="titulo">Título</label>
                 <input type="text" className="form-control" placeholder="" name="titulo" onChange={(evento)=>{setTitulo(evento.target.value)}} required />
                </div>
                <div className="form-group">
                    <label htmlFor="resumo">Resumo</label>
                    <textarea className="form-control" id="exampleFormControlTextarea1" rows="3" name="resumo"onChange={(evento)=>{setResumo(evento.target.value)}} required=""></textarea>
                </div>
                
                <div className="form-group">
                    <label htmlFor="editora">Editora</label>
                    <select name="editora" className="form-control" id="exampleFormControlSelect1" onChange={tratarCombo} required>
                     <option></option>
                     {opcoes}
                </select>
            </div>
                
            <div className="form-group">
                 <label htmlFor="autores">Autores</label> 
                 <textarea name="autores" className="form-control" id="exampleFormControlTextarea1" rows="2"onChange={(evento)=>{setAutores(evento.target.value)}}></textarea>
             </div>

            <button type="submit" className="btn btn-primary">Salvar dados</button>
        </form>
    </main>
    )
}
export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../Editora';
import { Livro } from '../Livro';

import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit{

  public livro: Livro = new Livro;

  public autoresForm: string = "";

  public editoras : Array<Editora>=[];

  constructor(
    private servEditora : ControleEditoraService,
    private servLivros : ControleLivrosService,
    private router : Router
    ){
      this.servEditora = servEditora;
      this.servLivros = servLivros;
      this.router = router;
    }
  ngOnInit(): void {this.editoras = this.servEditora.getEditoras();}
  incluir():void{
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.adicionar(this.livro);
    this.router.navigateByUrl("/lista");
    }
  
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<main class='container-fluid'>
    <h2 style="margin: 25px;">Dados do Livro</h2>
  <form ngNativeValidate class="form-control" (ngSubmit)="incluir()">
      <div class="form-group">
          <label for="titulo">Título</label>
          <input [(ngModel)]="livro.titulo" type="text" class="form-control" placeholder="" name="titulo"required>
      </div>
      <div class="form-group">
          <label for="resumo">Resumo</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
              [(ngModel)]="livro.resumo" name="resumo" required=""></textarea>
      </div>
      <div class="form-group">
          <label for="editora">Editora</label>
          <select name="editora" class="form-control" id="exampleFormControlSelect1"[(ngModel)]="livro.codEditora" required>
              <option *ngFor="let editora of editoras" value="{{editora.codEditora}}">
                  {{editora.nome}} 
              </option>
          </select>
      </div>
      <div class="form-group">
          <label for="autores">Autores</label>
          <textarea name="autores" class="form-control" id="exampleFormControlTextarea1" rows="2"
              [(ngModel)]="autoresForm"required></textarea>
      </div>

      <button type="submit" class="btn btn-primary" style="margin:15px 0 ;">Salvar dados</button>
  </form>
</main>
